trigger:
- master
- main
- refs/tags/v*

jobs:
- job: apps
  pool:
    vmImage: windows-latest  

  variables:
    buildConfiguration: 'Release'

  steps:
  - task: UseGitVersion@5
    inputs:
      versionSpec: '5.x'

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: 5.x

  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      restoreArguments: '--disable-parallel'
      feedsToUse: 'config'
      nugetConfigPath: './nuget.config'

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --collect "Code coverage" --no-build'

  - task: DotNetCoreCLI@2
    displayName: publish zero app
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/apps/src/*zero*/*.csproj'''
      arguments:  '--runtime win-x64 --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)\zero'
    
  - task: PublishBuildArtifacts@1
    displayName: upload app artifacts
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)\zero'
      ArtifactName: 'zero'