trigger:
- master
- main
- refs/tags/v*

jobs:
- job: apps
  pool:
    vmImage: windows-latest  

  variables:
    buildConfiguration: 'Release'

  steps:
  - task: UseGitVersion@5
    inputs:
      versionSpec: '5.x'

  - task: NuGetCommand@2
    displayName: solution nuget restore
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'config'
      nugetConfigPath: './nuget.config'

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      projects: 'test/**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --collect "Code coverage" --no-build'

  - task: DotNetCoreCLI@2
    displayName: publish zero app
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/apps/**/*-zero/*.csproj'
      arguments: '--runtime win-x64 --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)\zero_build'
      zipAfterPublish: false

  - task: CmdLine@2
    displayName: rename zero build
    inputs:
      script: 'ren haipa-zero bin'
      workingDirectory: '$(Build.ArtifactStagingDirectory)\zero_build'

  - task: ArchiveFiles@2
    displayName: pack zero build
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\zero_build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/apps/zero/eryph-zero.$(Build.BuildNumber).zip'

  - task: PublishBuildArtifacts@1
    displayName: upload zero artifact
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/apps/zero'
      ArtifactName: 'zero'