trigger:
- master
- main
- refs/tags/v*

jobs:
- job: apps
  pool:
    vmImage: windows-2022  

  variables:
   - group: 'eryph'
   - name: buildConfiguration
     value: 'Release'

  steps:
  - task: UseGitVersion@5
    inputs:
      versionSpec: '5.x'

  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'Authenticode.pfx'
      
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        $secName = "Authenticode.pfx"
        $tempDirectory = $env:AGENT_TEMPDIRECTORY        
        $pfxFilePath = Join-Path $tempDirectory $secName        
        $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
        $flag = [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable        
        $cert.Import($pfxFilePath, $env:AUTHENTICODE_PASSWORD, $flag)
    env:
      AUTHENTICODE_PASSWORD: $(AuthenticodePassword)

  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'config'
      nugetConfigPath: 'nuget.config'
      
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      projects: 'test/**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --collect "Code coverage" --no-build'

  - task: DotNetCoreCLI@2
    displayName: publish zero app
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/apps/**/*-zero/*.csproj'
      arguments: '--runtime win7-x64 --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)\zero_build'
      zipAfterPublish: false

  - task: ArchiveFiles@2
    displayName: pack zero build
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\zero_build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/apps/zero/eryph_zero_$(Build.BuildNumber)_windows_amd64.zip'

  - task: PublishBuildArtifacts@1
    displayName: upload zero artifact
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/apps/zero'
      ArtifactName: 'zero'