version: '3.4'

networks:
  internal:

services:
  rabbit:
    command:
      - rabbitmq-server
    container_name: rabbitmq
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - 8080:15672/tcp
      - 5672:5672/tcp
    networks:
      - internal
  mariadb:
    image: mariadb
    container_name: test-mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "rebus"
    #volumes:  
      #- ./store/mysql:/var/lib/mysql
    networks:
      - internal
    #volumes:
    #  - /storage/docker/mysql-datadir:/var/lib/mysql

  eryph.controller:
    image: ${DOCKER_REGISTRY}eryphcontroller
    build:
      context: .
      dockerfile: src/Eryph.Controller/Dockerfile
    depends_on:
      - rabbit
      - mariadb
    networks:
      - internal
    environment:
      - MYSQL_CONNECTIONSTRING="Server=localhost;Port=3306;Database=rebus;Uid=root;Pwd=password;SslMode=none;"
      - RABBITMQ_CONNECTIONSTRING="amqp://guest:guest@rabbit""

 # Eryph.ApiEndpoint:
 #   image: ${DOCKER_REGISTRY}EryphApiEndpoint
 #   build:
 #     context: .
 #     dockerfile: src/Eryph.ApiEndpoint/Dockerfile
 #   depends_on:
 #     - rabbit
 #     - mariadb
 #  networks:
 #     - internal
