// <auto-generated />
using System;
using Eryph.StateDb.MySql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eryph.StateDb.MySql.Migrations
{
    [DbContext(typeof(MySqlStateStoreContext))]
    partial class MySqlStateStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Eryph.StateDb.Model.CatletDrive", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("AttachedDiskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CatletId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttachedDiskId");

                    b.HasIndex("CatletId");

                    b.ToTable("CatletDrives");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.CatletMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.CatletMetadataGene", b =>
                {
                    b.Property<Guid>("MetadataId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UniqueGeneIndex")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GeneSet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MetadataId", "UniqueGeneIndex");

                    b.HasIndex("UniqueGeneIndex");

                    b.ToTable("MetadataGenes");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.CatletNetworkAdapter", b =>
                {
                    b.Property<Guid>("CatletId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SwitchName")
                        .HasColumnType("longtext");

                    b.HasKey("CatletId", "Id");

                    b.ToTable("CatletNetworkAdapters");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.Gene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GeneSet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("GeneType")
                        .HasColumnType("int");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastSeenAgent")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("UniqueGeneIndex")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UniqueGeneIndex", "LastSeenAgent")
                        .IsUnique();

                    b.ToTable("Genes");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.IpAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<Guid>("NetworkPortId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SubnetId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("NetworkPortId");

                    b.HasIndex("SubnetId");

                    b.ToTable("IpAssignment");

                    b.HasDiscriminator().HasValue("IpAssignment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Eryph.StateDb.Model.IpPool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstIp")
                        .HasColumnType("longtext");

                    b.Property<string>("IpNetwork")
                        .HasColumnType("longtext");

                    b.Property<string>("LastIp")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NextIp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<Guid>("SubnetId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SubnetId");

                    b.ToTable("IpPools");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.NetworkPort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressName")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.ToTable("NetworkPorts");

                    b.HasDiscriminator().HasValue("NetworkPort");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Eryph.StateDb.Model.OperationLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("TaskId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.OperationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResultData")
                        .HasColumnType("longtext");

                    b.Property<string>("ResultType")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.OperationProjectModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("OperationProjectModel");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.OperationResourceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.ToTable("OperationResources");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.OperationTaskModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AgentName")
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ParentTaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceProjectName")
                        .HasColumnType("longtext");

                    b.Property<int?>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("OperationTasks");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("BeingDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.ProjectRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasAlternateKey("ProjectId", "IdentityId", "RoleId");

                    b.ToTable("ProjectRoles");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.ReportedNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CatletId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DnsServerAddresses")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IPv4DefaultGateway")
                        .HasColumnType("longtext");

                    b.Property<string>("IPv6DefaultGateway")
                        .HasColumnType("longtext");

                    b.Property<string>("IpV4Addresses")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IpV4Subnets")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IpV6Addresses")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IpV6Subnets")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MacAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("PortName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CatletId");

                    b.ToTable("ReportedNetworks");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Eryph.StateDb.Model.Subnet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("DnsDomain")
                        .HasColumnType("longtext");

                    b.Property<string>("IpNetwork")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Subnet");

                    b.HasDiscriminator().HasValue("Subnet");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Eryph.StateDb.Model.TaskProgressEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskProgress");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.IpPoolAssignment", b =>
                {
                    b.HasBaseType("Eryph.StateDb.Model.IpAssignment");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("char(36)");

                    b.HasIndex("PoolId", "Number")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("IpPoolAssignment");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.FloatingNetworkPort", b =>
                {
                    b.HasBaseType("Eryph.StateDb.Model.NetworkPort");

                    b.Property<string>("PoolName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("FloatingNetworkPort");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.VirtualNetworkPort", b =>
                {
                    b.HasBaseType("Eryph.StateDb.Model.NetworkPort");

                    b.Property<Guid?>("FloatingPortId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("NetworkId")
                        .HasColumnType("char(36)");

                    b.HasIndex("FloatingPortId")
                        .IsUnique();

                    b.HasIndex("NetworkId");

                    b.HasDiscriminator().HasValue("VirtualNetworkPort");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.Catlet", b =>
                {
                    b.HasBaseType("Eryph.StateDb.Model.Resource");

                    b.Property<string>("AgentName")
                        .HasColumnType("longtext");

                    b.Property<int>("CatletType")
                        .HasColumnType("int");

                    b.Property<int>("CpuCount")
                        .HasColumnType("int");

                    b.Property<string>("DataStore")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Frozen")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("LastSeenState")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("MaximumMemory")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MetadataId")
                        .HasColumnType("char(36)");

                    b.Property<long>("MinimumMemory")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<string>("SecureBootTemplate")
                        .HasColumnType("longtext");

                    b.Property<long>("StartupMemory")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StorageIdentifier")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("UpTime")
                        .HasColumnType("time(6)");

                    b.Property<Guid>("VMId")
                        .HasColumnType("char(36)");

                    b.HasIndex("HostId");

                    b.ToTable("Catlets");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.CatletFarm", b =>
                {
                    b.HasBaseType("Eryph.StateDb.Model.Resource");

                    b.Property<DateTimeOffset>("LastInventory")
                        .HasColumnType("datetime(6)");

                    b.ToTable("CatletFarms");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.VirtualDisk", b =>
                {
                    b.HasBaseType("Eryph.StateDb.Model.Resource");

                    b.Property<string>("DataStore")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("DiskIdentifier")
                        .HasColumnType("char(36)");

                    b.Property<int>("DiskType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<bool>("Frozen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GeneArchitecture")
                        .HasColumnType("longtext");

                    b.Property<string>("GeneName")
                        .HasColumnType("longtext");

                    b.Property<string>("GeneSet")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastSeenAgent")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ParentPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StorageIdentifier")
                        .HasColumnType("longtext");

                    b.Property<string>("UniqueGeneIndex")
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("UsedSizeBytes")
                        .HasColumnType("bigint");

                    b.HasIndex("ParentId");

                    b.HasIndex("UniqueGeneIndex");

                    b.ToTable("VirtualDisks");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.VirtualNetwork", b =>
                {
                    b.HasBaseType("Eryph.StateDb.Model.Resource");

                    b.Property<string>("IpNetwork")
                        .HasColumnType("longtext");

                    b.Property<string>("NetworkProvider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("VirtualNetworks");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.ProviderSubnet", b =>
                {
                    b.HasBaseType("Eryph.StateDb.Model.Subnet");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("ProviderSubnet");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.VirtualNetworkSubnet", b =>
                {
                    b.HasBaseType("Eryph.StateDb.Model.Subnet");

                    b.Property<int>("DhcpLeaseTime")
                        .HasColumnType("int");

                    b.Property<string>("DnsServersV4")
                        .HasColumnType("longtext");

                    b.Property<int>("MTU")
                        .HasColumnType("int");

                    b.Property<Guid>("NetworkId")
                        .HasColumnType("char(36)");

                    b.HasIndex("NetworkId");

                    b.HasDiscriminator().HasValue("VirtualNetworkSubnet");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.CatletNetworkPort", b =>
                {
                    b.HasBaseType("Eryph.StateDb.Model.VirtualNetworkPort");

                    b.Property<Guid>("CatletMetadataId")
                        .HasColumnType("char(36)");

                    b.HasIndex("CatletMetadataId");

                    b.HasDiscriminator().HasValue("CatletNetworkPort");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.NetworkRouterPort", b =>
                {
                    b.HasBaseType("Eryph.StateDb.Model.VirtualNetworkPort");

                    b.Property<Guid>("RoutedNetworkId")
                        .HasColumnType("char(36)");

                    b.HasIndex("RoutedNetworkId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("NetworkRouterPort");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.ProviderRouterPort", b =>
                {
                    b.HasBaseType("Eryph.StateDb.Model.VirtualNetworkPort");

                    b.Property<string>("PoolName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubnetName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("NetworkPorts", t =>
                        {
                            t.Property("PoolName")
                                .HasColumnName("ProviderRouterPort_PoolName");

                            t.Property("SubnetName")
                                .HasColumnName("ProviderRouterPort_SubnetName");
                        });

                    b.HasDiscriminator().HasValue("ProviderRouterPort");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.CatletDrive", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.VirtualDisk", "AttachedDisk")
                        .WithMany("AttachedDrives")
                        .HasForeignKey("AttachedDiskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Eryph.StateDb.Model.Catlet", "Catlet")
                        .WithMany("Drives")
                        .HasForeignKey("CatletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttachedDisk");

                    b.Navigation("Catlet");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.CatletMetadataGene", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.CatletMetadata", null)
                        .WithMany("Genes")
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eryph.StateDb.Model.CatletNetworkAdapter", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.Catlet", "Catlet")
                        .WithMany("NetworkAdapters")
                        .HasForeignKey("CatletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catlet");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.IpAssignment", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.NetworkPort", "NetworkPort")
                        .WithMany("IpAssignments")
                        .HasForeignKey("NetworkPortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eryph.StateDb.Model.Subnet", "Subnet")
                        .WithMany("IpAssignments")
                        .HasForeignKey("SubnetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("NetworkPort");

                    b.Navigation("Subnet");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.IpPool", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.Subnet", "Subnet")
                        .WithMany("IpPools")
                        .HasForeignKey("SubnetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subnet");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.OperationLogEntry", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.OperationModel", "Operation")
                        .WithMany("LogEntries")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eryph.StateDb.Model.OperationTaskModel", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.OperationProjectModel", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.OperationModel", "Operation")
                        .WithMany("Projects")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eryph.StateDb.Model.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.OperationResourceModel", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.OperationModel", "Operation")
                        .WithMany("Resources")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.OperationTaskModel", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.OperationModel", "Operation")
                        .WithMany("Tasks")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eryph.StateDb.Model.Project", null)
                        .WithMany("ReferencedTasks")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.Project", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.Tenant", "Tenant")
                        .WithMany("Projects")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.ProjectRoleAssignment", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.Project", "Project")
                        .WithMany("ProjectRoles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.ReportedNetwork", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.Catlet", "Catlet")
                        .WithMany("ReportedNetworks")
                        .HasForeignKey("CatletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catlet");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.Resource", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.Project", "Project")
                        .WithMany("Resources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.TaskProgressEntry", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.OperationTaskModel", "Task")
                        .WithMany("Progress")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.IpPoolAssignment", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.IpPool", "Pool")
                        .WithMany("IpAssignments")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.VirtualNetworkPort", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.FloatingNetworkPort", "FloatingPort")
                        .WithOne("AssignedPort")
                        .HasForeignKey("Eryph.StateDb.Model.VirtualNetworkPort", "FloatingPortId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Eryph.StateDb.Model.VirtualNetwork", "Network")
                        .WithMany("NetworkPorts")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FloatingPort");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.Catlet", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.CatletFarm", "Host")
                        .WithMany("Catlets")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Host");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.VirtualDisk", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.VirtualDisk", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.VirtualNetworkSubnet", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.VirtualNetwork", "Network")
                        .WithMany("Subnets")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Network");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.CatletNetworkPort", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.CatletMetadata", null)
                        .WithMany()
                        .HasForeignKey("CatletMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eryph.StateDb.Model.NetworkRouterPort", b =>
                {
                    b.HasOne("Eryph.StateDb.Model.VirtualNetwork", "RoutedNetwork")
                        .WithOne("RouterPort")
                        .HasForeignKey("Eryph.StateDb.Model.NetworkRouterPort", "RoutedNetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoutedNetwork");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.CatletMetadata", b =>
                {
                    b.Navigation("Genes");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.IpPool", b =>
                {
                    b.Navigation("IpAssignments");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.NetworkPort", b =>
                {
                    b.Navigation("IpAssignments");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.OperationModel", b =>
                {
                    b.Navigation("LogEntries");

                    b.Navigation("Projects");

                    b.Navigation("Resources");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.OperationTaskModel", b =>
                {
                    b.Navigation("Progress");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.Project", b =>
                {
                    b.Navigation("ProjectRoles");

                    b.Navigation("ReferencedTasks");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.Subnet", b =>
                {
                    b.Navigation("IpAssignments");

                    b.Navigation("IpPools");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.Tenant", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.FloatingNetworkPort", b =>
                {
                    b.Navigation("AssignedPort");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.Catlet", b =>
                {
                    b.Navigation("Drives");

                    b.Navigation("NetworkAdapters");

                    b.Navigation("ReportedNetworks");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.CatletFarm", b =>
                {
                    b.Navigation("Catlets");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.VirtualDisk", b =>
                {
                    b.Navigation("AttachedDrives");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("Eryph.StateDb.Model.VirtualNetwork", b =>
                {
                    b.Navigation("NetworkPorts");

                    b.Navigation("RouterPort");

                    b.Navigation("Subnets");
                });
#pragma warning restore 612, 618
        }
    }
}
