namespace Eryph.VmManagement;

public enum PowershellFailureCategory
{
    NotSpecified,
    OpenError,
    CloseError,
    DeviceError,
    DeadlockDetected,
    InvalidArgument,
    InvalidData,
    InvalidOperation,
    InvalidResult,
    InvalidType,
    MetadataError,
    NotImplemented,
    NotInstalled,
    ObjectNotFound,
    OperationStopped,
    OperationTimeout,
    SyntaxError,
    ParserError,
    PermissionDenied,
    ResourceBusy,
    ResourceExists,
    ResourceUnavailable,
    ReadError,
    WriteError,
    FromStdErr,
    SecurityError,
    ProtocolError,
    ConnectionError,
    AuthenticationError,
    LimitsExceeded,
    QuotaExceeded,
    NotEnabled,
}
