// <auto-generated />
using System;
using HyperVPlus.StateDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HyperVPlus.StateDb.MySql.Migrations
{
    [DbContext(typeof(StateStoreContext))]
    [Migration("20180903141510_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HyperVPlus.StateDb.Model.Agent", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Name");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("HyperVPlus.StateDb.Model.IpV4Address", b =>
                {
                    b.Property<Guid>("MachineId");

                    b.Property<string>("Address");

                    b.HasKey("MachineId", "Address");

                    b.ToTable("Ipv4Addresses");
                });

            modelBuilder.Entity("HyperVPlus.StateDb.Model.IpV6Address", b =>
                {
                    b.Property<Guid>("MachineId");

                    b.Property<string>("Address");

                    b.HasKey("MachineId", "Address");

                    b.ToTable("Ipv6Addresses");
                });

            modelBuilder.Entity("HyperVPlus.StateDb.Model.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("HyperVPlus.StateDb.Model.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("MachineGuid");

                    b.HasKey("Id");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("HyperVPlus.StateDb.Model.OperationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Message");

                    b.Property<Guid?>("OperationId");

                    b.Property<DateTimeOffset>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("HyperVPlus.StateDb.Model.IpV4Address", b =>
                {
                    b.HasOne("HyperVPlus.StateDb.Model.Machine", "Machine")
                        .WithMany("IpV4Addresses")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HyperVPlus.StateDb.Model.IpV6Address", b =>
                {
                    b.HasOne("HyperVPlus.StateDb.Model.Machine", "Machine")
                        .WithMany("IpV6Addresses")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HyperVPlus.StateDb.Model.Machine", b =>
                {
                    b.HasOne("HyperVPlus.StateDb.Model.Agent", "Agent")
                        .WithMany("Machines")
                        .HasForeignKey("Name");
                });

            modelBuilder.Entity("HyperVPlus.StateDb.Model.OperationLog", b =>
                {
                    b.HasOne("HyperVPlus.StateDb.Model.Operation", "Operation")
                        .WithMany("LogEntries")
                        .HasForeignKey("OperationId");
                });
#pragma warning restore 612, 618
        }
    }
}
