// <auto-generated />
using System;
using JetBrains.Annotations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace HyperVPlus.StateDb.MySql.Migrations
{
    [DbContext(typeof(StateStoreContext))]
    [UsedImplicitly]
    partial class StateStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HyperVPlus.StateDb.Model.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("HyperVPlus.StateDb.Model.OperationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Message");

                    b.Property<Guid?>("OperationId");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("HyperVPlus.StateDb.Model.OperationLog", b =>
                {
                    b.HasOne("HyperVPlus.StateDb.Model.Operation", "Operation")
                        .WithMany("LogEntries")
                        .HasForeignKey("OperationId");
                });
#pragma warning restore 612, 618
        }
    }
}
